run:
  tests: true
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 7m
  skip-files:
    - "protocol/chainlib/chainproxy/rpcInterfaceMessages/grpcMessage.go"
    - "protocol/chainlib/grpc.go"
    - "protocol/chainlib/grpcproxy/dyncodec/remote_grpc_reflection.go"
    - "protocol/chainlib/grpcproxy/dyncodec/remote_relayer.go"
    - "protocol/chainlib/grpcproxy/dyncodec/remotes_test.go"
    - "ecosystem/lavajs/*"
    - "ecosystem/lava-sdk/*"

linters:
  disable-all: true
  #for list of linters and what they do: https://golangci-lint.run/usage/linters/
  enable:
    - dogsled
    - exportloopref
    - gocritic
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    #- unused we have a lot of unused code that we don't want to delete
    - forcetypeassert
    - gofmt
    - goimports
    - importas
    - ineffassign
    - nilnil
    - typecheck
    - unconvert
    - whitespace

issues:
  exclude-files:
    - "protocol/chainlib/chainproxy/rpcInterfaceMessages/grpcMessage.go"
    - "protocol/chainlib/grpc.go"
    - "protocol/chainlib/grpcproxy/dyncodec/remote_grpc_reflection.go"
    - "protocol/chainlib/grpcproxy/dyncodec/remote_relayer.go"
    - "protocol/chainlib/grpcproxy/dyncodec/remotes_test.go"
    - "ecosystem/lavajs/*"
    - "ecosystem/lava-sdk/*"
  exclude-rules:
    - text: "singleCaseSwitch"
      linters:
        - gocritic
    - text: "ifElseChain"
      linters:
        - gocritic
    - text: "ST1003:"
      linters:
        - stylecheck
    # FIXME: Disabled until golangci-lint updates stylecheck with this fix:
    # https://github.com/dominikh/go-tools/issues/389
    - text: "ST1016:"
      linters:
        - stylecheck
    - text: 'SA1019:.*"github.com/golang/protobuf/proto" is deprecated.*' # proto is deprecated, but some places couldn't be removed
      linters:
        - staticcheck
    - path: "migrations"
      text: "SA1019:"
      linters:
        - staticcheck

  max-issues-per-linter: 10000
  max-same-issues: 10000

linters-settings:
  dogsled:
    max-blank-identifiers: 5
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
