version: 1
build:
  main: cmd/lavad
  binary: lavad
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 50000000000000ulava
- name: bob
  coins:
  - 50000000000000ulava
- name: user1
  coins:
  - 50000000000000ulava
- name: user2
  coins:
  - 50000000000000ulava
- name: user3
  coins:
  - 50000000000000ulava
- name: user4
  coins:
  - 50000000000000ulava
- name: servicer1
  coins:
  - 50000000000000ulava
- name: servicer2
  coins:
  - 50000000000000ulava
- name: servicer3
  coins:
  - 50000000000000ulava
- name: servicer4
  coins:
  - 50000000000000ulava
- name: servicer5
  coins:
  - 50000000000000ulava
- name: servicer6
  coins:
  - 50000000000000ulava
- name: servicer7
  coins:
  - 50000000000000ulava
- name: servicer8
  coins:
  - 50000000000000ulava
- name: servicer9
  coins:
  - 50000000000000ulava
- name: servicer10
  coins:
  - 50000000000000ulava
faucet:
  name: bob
  coins:
  - 100000ulava
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: ulava
      voting_params:
        voting_period: 3s
    mint:
      params:
        mint_denom: ulava
    staking:
      params:
        bond_denom: ulava
  chain_id: lava
validators:
- name: alice
  bonded: 100000000000ulava
  app:
    minimum-gas-prices: 0.00002ulava
