// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: conflict/conflict_vote.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Provider struct {
	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Response []byte `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ff6a0d8edaa7f1, []int{0}
}
func (m *Provider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return m.Size()
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Provider) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

type Voter struct {
	Account      string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	HashResponse []byte `protobuf:"bytes,2,opt,name=hashResponse,proto3" json:"hashResponse,omitempty"`
}

func (m *Voter) Reset()         { *m = Voter{} }
func (m *Voter) String() string { return proto.CompactTextString(m) }
func (*Voter) ProtoMessage()    {}
func (*Voter) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ff6a0d8edaa7f1, []int{1}
}
func (m *Voter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Voter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Voter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Voter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Voter.Merge(m, src)
}
func (m *Voter) XXX_Size() int {
	return m.Size()
}
func (m *Voter) XXX_DiscardUnknown() {
	xxx_messageInfo_Voter.DiscardUnknown(m)
}

var xxx_messageInfo_Voter proto.InternalMessageInfo

func (m *Voter) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Voter) GetHashResponse() []byte {
	if m != nil {
		return m.HashResponse
	}
	return nil
}

type ConflictVote struct {
	Index          string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	VoteID         uint64   `protobuf:"varint,2,opt,name=voteID,proto3" json:"voteID,omitempty"`
	VoteDeadline   uint64   `protobuf:"varint,3,opt,name=voteDeadline,proto3" json:"voteDeadline,omitempty"`
	VoteStartBlock uint64   `protobuf:"varint,4,opt,name=voteStartBlock,proto3" json:"voteStartBlock,omitempty"`
	VoteIsCommit   bool     `protobuf:"varint,5,opt,name=voteIsCommit,proto3" json:"voteIsCommit,omitempty"`
	ChainID        string   `protobuf:"bytes,6,opt,name=chainID,proto3" json:"chainID,omitempty"`
	ApiUrl         string   `protobuf:"bytes,7,opt,name=apiUrl,proto3" json:"apiUrl,omitempty"`
	RequestData    []byte   `protobuf:"bytes,8,opt,name=requestData,proto3" json:"requestData,omitempty"`
	RequestBlock   uint64   `protobuf:"varint,9,opt,name=requestBlock,proto3" json:"requestBlock,omitempty"`
	FirstProvider  Provider `protobuf:"bytes,10,opt,name=firstProvider,proto3" json:"firstProvider"`
	SecondProvider Provider `protobuf:"bytes,11,opt,name=secondProvider,proto3" json:"secondProvider"`
	Voters         []Voter  `protobuf:"bytes,12,rep,name=voters,proto3" json:"voters"`
}

func (m *ConflictVote) Reset()         { *m = ConflictVote{} }
func (m *ConflictVote) String() string { return proto.CompactTextString(m) }
func (*ConflictVote) ProtoMessage()    {}
func (*ConflictVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5ff6a0d8edaa7f1, []int{2}
}
func (m *ConflictVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConflictVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConflictVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConflictVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConflictVote.Merge(m, src)
}
func (m *ConflictVote) XXX_Size() int {
	return m.Size()
}
func (m *ConflictVote) XXX_DiscardUnknown() {
	xxx_messageInfo_ConflictVote.DiscardUnknown(m)
}

var xxx_messageInfo_ConflictVote proto.InternalMessageInfo

func (m *ConflictVote) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ConflictVote) GetVoteID() uint64 {
	if m != nil {
		return m.VoteID
	}
	return 0
}

func (m *ConflictVote) GetVoteDeadline() uint64 {
	if m != nil {
		return m.VoteDeadline
	}
	return 0
}

func (m *ConflictVote) GetVoteStartBlock() uint64 {
	if m != nil {
		return m.VoteStartBlock
	}
	return 0
}

func (m *ConflictVote) GetVoteIsCommit() bool {
	if m != nil {
		return m.VoteIsCommit
	}
	return false
}

func (m *ConflictVote) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *ConflictVote) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

func (m *ConflictVote) GetRequestData() []byte {
	if m != nil {
		return m.RequestData
	}
	return nil
}

func (m *ConflictVote) GetRequestBlock() uint64 {
	if m != nil {
		return m.RequestBlock
	}
	return 0
}

func (m *ConflictVote) GetFirstProvider() Provider {
	if m != nil {
		return m.FirstProvider
	}
	return Provider{}
}

func (m *ConflictVote) GetSecondProvider() Provider {
	if m != nil {
		return m.SecondProvider
	}
	return Provider{}
}

func (m *ConflictVote) GetVoters() []Voter {
	if m != nil {
		return m.Voters
	}
	return nil
}

func init() {
	proto.RegisterType((*Provider)(nil), "lavanet.lava.conflict.Provider")
	proto.RegisterType((*Voter)(nil), "lavanet.lava.conflict.Voter")
	proto.RegisterType((*ConflictVote)(nil), "lavanet.lava.conflict.ConflictVote")
}

func init() { proto.RegisterFile("conflict/conflict_vote.proto", fileDescriptor_c5ff6a0d8edaa7f1) }

var fileDescriptor_c5ff6a0d8edaa7f1 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xae, 0xe9, 0x8f, 0x75, 0x6e, 0xd9, 0xc1, 0x1a, 0xc8, 0x9a, 0xa6, 0x2c, 0xca, 0x01, 0xe5,
	0x94, 0x48, 0xe3, 0xc6, 0x09, 0x65, 0xe1, 0x50, 0x21, 0x24, 0x14, 0x04, 0x07, 0x2e, 0xc8, 0x73,
	0xbc, 0xc6, 0x22, 0xb5, 0x83, 0xed, 0x56, 0xe3, 0xbf, 0xe0, 0xcf, 0xda, 0x71, 0x47, 0x4e, 0x08,
	0xb5, 0xff, 0x06, 0x07, 0x64, 0xc7, 0xa9, 0x96, 0x0a, 0x90, 0x38, 0xf9, 0x7d, 0x9f, 0xbf, 0xf7,
	0xf9, 0x3d, 0xbf, 0x07, 0xcf, 0xa9, 0x14, 0x37, 0x35, 0xa7, 0x26, 0xed, 0x82, 0x4f, 0x1b, 0x69,
	0x58, 0xd2, 0x28, 0x69, 0x24, 0x7a, 0x52, 0x93, 0x0d, 0x11, 0xcc, 0x24, 0xf6, 0x4c, 0x3a, 0xc5,
	0xd9, 0xe9, 0x52, 0x2e, 0xa5, 0x53, 0xa4, 0x36, 0x6a, 0xc5, 0xd1, 0x4b, 0x38, 0x7d, 0xab, 0xe4,
	0x86, 0x97, 0x4c, 0x21, 0x0c, 0x8f, 0x08, 0xa5, 0x72, 0x2d, 0x0c, 0x06, 0x21, 0x88, 0x8f, 0x8b,
	0x0e, 0xa2, 0x33, 0x38, 0x55, 0x4c, 0x37, 0x52, 0x68, 0x86, 0x1f, 0x85, 0x20, 0x9e, 0x17, 0x7b,
	0x1c, 0xbd, 0x82, 0xe3, 0x0f, 0xd2, 0xfc, 0x33, 0x3d, 0x82, 0xf3, 0x8a, 0xe8, 0xaa, 0xe8, 0x5b,
	0xf4, 0xb8, 0xe8, 0xd7, 0x10, 0xce, 0xaf, 0x7c, 0xad, 0xd6, 0x0f, 0x9d, 0xc2, 0x31, 0x17, 0x25,
	0xbb, 0xf5, 0x66, 0x2d, 0x40, 0x4f, 0xe1, 0xc4, 0xb6, 0xba, 0xc8, 0x9d, 0xc9, 0xa8, 0xf0, 0xc8,
	0x3e, 0x61, 0xa3, 0x9c, 0x91, 0xb2, 0xe6, 0x82, 0xe1, 0xa1, 0xbb, 0xed, 0x71, 0xe8, 0x19, 0x3c,
	0xb1, 0xf8, 0x9d, 0x21, 0xca, 0x64, 0xb5, 0xa4, 0x9f, 0xf1, 0xc8, 0xa9, 0x0e, 0xd8, 0xce, 0x6b,
	0xa1, 0xaf, 0xe4, 0x6a, 0xc5, 0x0d, 0x1e, 0x87, 0x20, 0x9e, 0x16, 0x3d, 0xce, 0x36, 0x4b, 0x2b,
	0xc2, 0xc5, 0x22, 0xc7, 0x93, 0xb6, 0x59, 0x0f, 0x6d, 0x85, 0xa4, 0xe1, 0xef, 0x55, 0x8d, 0x8f,
	0xdc, 0x85, 0x47, 0x28, 0x84, 0x33, 0xc5, 0xbe, 0xac, 0x99, 0x36, 0x39, 0x31, 0x04, 0x4f, 0xdd,
	0x1f, 0x3c, 0xa4, 0xec, 0xbb, 0x1e, 0xb6, 0xd5, 0x1d, 0xb7, 0x3d, 0x3c, 0xe4, 0xd0, 0x6b, 0xf8,
	0xf8, 0x86, 0x2b, 0x6d, 0xba, 0xa1, 0x61, 0x18, 0x82, 0x78, 0x76, 0x79, 0x91, 0xfc, 0x71, 0xe8,
	0x49, 0x27, 0xcb, 0x46, 0x77, 0x3f, 0x2e, 0x06, 0x45, 0x3f, 0x17, 0xbd, 0x81, 0x27, 0x9a, 0x51,
	0x29, 0xca, 0xbd, 0xdb, 0xec, 0x7f, 0xdc, 0x0e, 0x92, 0xd1, 0x8b, 0x76, 0x36, 0x4a, 0xe3, 0x79,
	0x38, 0x8c, 0x67, 0x97, 0xe7, 0x7f, 0xb1, 0x71, 0xeb, 0xe2, 0x3d, 0x7c, 0x46, 0x96, 0xdd, 0x6d,
	0x03, 0x70, 0xbf, 0x0d, 0xc0, 0xcf, 0x6d, 0x00, 0xbe, 0xed, 0x82, 0xc1, 0xfd, 0x2e, 0x18, 0x7c,
	0xdf, 0x05, 0x83, 0x8f, 0xf1, 0x92, 0x9b, 0x6a, 0x7d, 0x9d, 0x50, 0xb9, 0x4a, 0xbd, 0x9f, 0x3b,
	0xd3, 0xdb, 0xfd, 0xf6, 0xa7, 0xe6, 0x6b, 0xc3, 0xf4, 0xf5, 0xc4, 0xad, 0xf4, 0xf3, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xad, 0xd3, 0xe5, 0x39, 0x1f, 0x03, 0x00, 0x00,
}

func (m *Provider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Provider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Provider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Response) > 0 {
		i -= len(m.Response)
		copy(dAtA[i:], m.Response)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.Response)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Voter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Voter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Voter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HashResponse) > 0 {
		i -= len(m.HashResponse)
		copy(dAtA[i:], m.HashResponse)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.HashResponse)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConflictVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConflictVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConflictVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Voters) > 0 {
		for iNdEx := len(m.Voters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Voters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConflictVote(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	{
		size, err := m.SecondProvider.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintConflictVote(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size, err := m.FirstProvider.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintConflictVote(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.RequestBlock != 0 {
		i = encodeVarintConflictVote(dAtA, i, uint64(m.RequestBlock))
		i--
		dAtA[i] = 0x48
	}
	if len(m.RequestData) > 0 {
		i -= len(m.RequestData)
		copy(dAtA[i:], m.RequestData)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.RequestData)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ApiUrl) > 0 {
		i -= len(m.ApiUrl)
		copy(dAtA[i:], m.ApiUrl)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.ApiUrl)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0x32
	}
	if m.VoteIsCommit {
		i--
		if m.VoteIsCommit {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.VoteStartBlock != 0 {
		i = encodeVarintConflictVote(dAtA, i, uint64(m.VoteStartBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.VoteDeadline != 0 {
		i = encodeVarintConflictVote(dAtA, i, uint64(m.VoteDeadline))
		i--
		dAtA[i] = 0x18
	}
	if m.VoteID != 0 {
		i = encodeVarintConflictVote(dAtA, i, uint64(m.VoteID))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintConflictVote(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConflictVote(dAtA []byte, offset int, v uint64) int {
	offset -= sovConflictVote(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Provider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	l = len(m.Response)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	return n
}

func (m *Voter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	l = len(m.HashResponse)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	return n
}

func (m *ConflictVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	if m.VoteID != 0 {
		n += 1 + sovConflictVote(uint64(m.VoteID))
	}
	if m.VoteDeadline != 0 {
		n += 1 + sovConflictVote(uint64(m.VoteDeadline))
	}
	if m.VoteStartBlock != 0 {
		n += 1 + sovConflictVote(uint64(m.VoteStartBlock))
	}
	if m.VoteIsCommit {
		n += 2
	}
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	l = len(m.ApiUrl)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	l = len(m.RequestData)
	if l > 0 {
		n += 1 + l + sovConflictVote(uint64(l))
	}
	if m.RequestBlock != 0 {
		n += 1 + sovConflictVote(uint64(m.RequestBlock))
	}
	l = m.FirstProvider.Size()
	n += 1 + l + sovConflictVote(uint64(l))
	l = m.SecondProvider.Size()
	n += 1 + l + sovConflictVote(uint64(l))
	if len(m.Voters) > 0 {
		for _, e := range m.Voters {
			l = e.Size()
			n += 1 + l + sovConflictVote(uint64(l))
		}
	}
	return n
}

func sovConflictVote(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConflictVote(x uint64) (n int) {
	return sovConflictVote(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Provider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConflictVote
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Provider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Provider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Response = append(m.Response[:0], dAtA[iNdEx:postIndex]...)
			if m.Response == nil {
				m.Response = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConflictVote(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConflictVote
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Voter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConflictVote
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Voter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Voter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HashResponse", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HashResponse = append(m.HashResponse[:0], dAtA[iNdEx:postIndex]...)
			if m.HashResponse == nil {
				m.HashResponse = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConflictVote(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConflictVote
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConflictVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConflictVote
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConflictVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConflictVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteID", wireType)
			}
			m.VoteID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteDeadline", wireType)
			}
			m.VoteDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteDeadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteStartBlock", wireType)
			}
			m.VoteStartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VoteStartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteIsCommit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VoteIsCommit = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequestData = append(m.RequestData[:0], dAtA[iNdEx:postIndex]...)
			if m.RequestData == nil {
				m.RequestData = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestBlock", wireType)
			}
			m.RequestBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstProvider", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FirstProvider.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecondProvider", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SecondProvider.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConflictVote
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConflictVote
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voters = append(m.Voters, Voter{})
			if err := m.Voters[len(m.Voters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConflictVote(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConflictVote
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConflictVote(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConflictVote
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConflictVote
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConflictVote
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConflictVote
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConflictVote
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConflictVote        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConflictVote          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConflictVote = fmt.Errorf("proto: unexpected end of group")
)
