endpoints:
    - api-interface: jsonrpc
      chain-id: ETH1
      network-address:
        address: "127.0.0.1:2224"
      node-urls:
        - url: my-eth-node.com/eth-bundler/ws
          addons:
            - bundler