endpoints:
  - api-interface: jsonrpc
    chain-id: STRK
    network-address:
      address: "127.0.0.1:2220"
    node-urls:
      - url: wss://starknet.api.onfinality.io/public-ws
        internal-path: /ws/rpc/v0_9
      - url: wss://starknet.api.onfinality.io/public-ws
        internal-path: /ws/rpc/v0_8
      - url: wss://starknet.api.onfinality.io/public-ws
      - url: https://starknet-mainnet.public.blastapi.io
