endpoints:
  - api-interface: jsonrpc
    chain-id: STRK
    network-address:
      address: "127.0.0.1:2220"
    node-urls:
      - url: <wss url here>/ws
        internal-path: ""
      - url: <wss url here>/ws/rpc/v0_9
        internal-path: "/ws/rpc/v0_9"
      - url: <wss url here>/ws/rpc/v0_10
        internal-path: "/ws/rpc/v0_10"
      - url: <https url here>
        internal-path: ""
      - url: <https url here>/rpc/v0_9
        internal-path: "/rpc/v0_9"
      - url: <https url here>/rpc/v0_10
        internal-path: "/rpc/v0_10"
