endpoints:
    - api-interface: tendermintrpc
      chain-id: INDEX_REPLACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls:
        - url: REPLACE_THIS_URL
        - url: REPLACE_THIS_URL
          addons:
            - archive
        - url: REPLACE_THIS_URL
        - url: REPLACE_THIS_URL
          addons:
            - archive
    - api-interface: grpc
      chain-id: INDEX_REPLACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls: 
        - url: REPLACE_THIS_URL
        - url: REPLACE_THIS_URL
          addons:
            - archive
    - api-interface: rest
      chain-id: INDEX_REPLACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls: 
        - url: REPLACE_THIS_URL
        - url: REPLACE_THIS_URL
          addons:
            - archive
    - api-interface: jsonrpc
      chain-id: INDEX_REPLACE_THIS
      network-address:
        address: "127.0.0.1:2220"
      node-urls: 
        - url: REPLACE_THIS_URL
        - url: REPLACE_THIS_URL
          addons:
            - archive
