// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lavanet/lava/rewards/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetIprpcData struct {
	Authority          string     `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MinIprpcCost       types.Coin `protobuf:"bytes,2,opt,name=min_iprpc_cost,json=minIprpcCost,proto3" json:"min_iprpc_cost"`
	IprpcSubscriptions []string   `protobuf:"bytes,3,rep,name=iprpc_subscriptions,json=iprpcSubscriptions,proto3" json:"iprpc_subscriptions,omitempty"`
}

func (m *MsgSetIprpcData) Reset()         { *m = MsgSetIprpcData{} }
func (m *MsgSetIprpcData) String() string { return proto.CompactTextString(m) }
func (*MsgSetIprpcData) ProtoMessage()    {}
func (*MsgSetIprpcData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4c66e189226d78, []int{0}
}
func (m *MsgSetIprpcData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetIprpcData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetIprpcData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetIprpcData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetIprpcData.Merge(m, src)
}
func (m *MsgSetIprpcData) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetIprpcData) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetIprpcData.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetIprpcData proto.InternalMessageInfo

func (m *MsgSetIprpcData) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgSetIprpcData) GetMinIprpcCost() types.Coin {
	if m != nil {
		return m.MinIprpcCost
	}
	return types.Coin{}
}

func (m *MsgSetIprpcData) GetIprpcSubscriptions() []string {
	if m != nil {
		return m.IprpcSubscriptions
	}
	return nil
}

type MsgSetIprpcDataResponse struct {
}

func (m *MsgSetIprpcDataResponse) Reset()         { *m = MsgSetIprpcDataResponse{} }
func (m *MsgSetIprpcDataResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetIprpcDataResponse) ProtoMessage()    {}
func (*MsgSetIprpcDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4c66e189226d78, []int{1}
}
func (m *MsgSetIprpcDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetIprpcDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetIprpcDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetIprpcDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetIprpcDataResponse.Merge(m, src)
}
func (m *MsgSetIprpcDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetIprpcDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetIprpcDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetIprpcDataResponse proto.InternalMessageInfo

type MsgFundIprpc struct {
	Creator  string                                   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Duration uint64                                   `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Amounts  github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=amounts,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amounts"`
	Spec     string                                   `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (m *MsgFundIprpc) Reset()         { *m = MsgFundIprpc{} }
func (m *MsgFundIprpc) String() string { return proto.CompactTextString(m) }
func (*MsgFundIprpc) ProtoMessage()    {}
func (*MsgFundIprpc) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4c66e189226d78, []int{2}
}
func (m *MsgFundIprpc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundIprpc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundIprpc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundIprpc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundIprpc.Merge(m, src)
}
func (m *MsgFundIprpc) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundIprpc) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundIprpc.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundIprpc proto.InternalMessageInfo

func (m *MsgFundIprpc) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgFundIprpc) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MsgFundIprpc) GetAmounts() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *MsgFundIprpc) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type MsgFundIprpcResponse struct {
}

func (m *MsgFundIprpcResponse) Reset()         { *m = MsgFundIprpcResponse{} }
func (m *MsgFundIprpcResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFundIprpcResponse) ProtoMessage()    {}
func (*MsgFundIprpcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a4c66e189226d78, []int{3}
}
func (m *MsgFundIprpcResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFundIprpcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFundIprpcResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFundIprpcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFundIprpcResponse.Merge(m, src)
}
func (m *MsgFundIprpcResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFundIprpcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFundIprpcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFundIprpcResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSetIprpcData)(nil), "lavanet.lava.rewards.MsgSetIprpcData")
	proto.RegisterType((*MsgSetIprpcDataResponse)(nil), "lavanet.lava.rewards.MsgSetIprpcDataResponse")
	proto.RegisterType((*MsgFundIprpc)(nil), "lavanet.lava.rewards.MsgFundIprpc")
	proto.RegisterType((*MsgFundIprpcResponse)(nil), "lavanet.lava.rewards.MsgFundIprpcResponse")
}

func init() { proto.RegisterFile("lavanet/lava/rewards/tx.proto", fileDescriptor_6a4c66e189226d78) }

var fileDescriptor_6a4c66e189226d78 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x6f, 0x68, 0xc5, 0xa8, 0xa9, 0x40, 0x98, 0x8a, 0xb5, 0xd1, 0xc8, 0xaa, 0x48, 0x88, 0x6a,
	0xd2, 0x6c, 0x36, 0x6e, 0xbb, 0xb1, 0x01, 0x12, 0x87, 0x5e, 0xb2, 0x1b, 0x1c, 0x26, 0x27, 0xb1,
	0x32, 0x0b, 0x62, 0x47, 0x7e, 0xce, 0xd8, 0xbe, 0x02, 0x27, 0x3e, 0x07, 0x27, 0xbe, 0x04, 0x52,
	0x8f, 0x3b, 0x22, 0x0e, 0x80, 0xda, 0x03, 0x5f, 0x03, 0xd9, 0x49, 0xda, 0xae, 0xe2, 0xcf, 0x2e,
	0x79, 0x7f, 0x7e, 0x2f, 0xef, 0xfd, 0x7e, 0xcf, 0x36, 0x7a, 0xf8, 0x8e, 0x9d, 0x31, 0xc9, 0x0d,
	0xb5, 0x96, 0x6a, 0xfe, 0x9e, 0xe9, 0x14, 0xa8, 0x39, 0x27, 0x85, 0x56, 0x46, 0xe1, 0x7e, 0x0d,
	0x13, 0x6b, 0x49, 0x0d, 0xfb, 0xf7, 0x58, 0x2e, 0xa4, 0xa2, 0xee, 0x5b, 0x15, 0xfa, 0x41, 0xa2,
	0x20, 0x57, 0x40, 0x63, 0x06, 0x9c, 0x9e, 0xed, 0xc5, 0xdc, 0xb0, 0x3d, 0x9a, 0x28, 0x21, 0x6b,
	0xbc, 0x9f, 0xa9, 0x4c, 0x39, 0x97, 0x5a, 0xaf, 0xca, 0x86, 0x5f, 0x3c, 0x74, 0x77, 0x02, 0xd9,
	0x31, 0x37, 0xaf, 0x0a, 0x5d, 0x24, 0xcf, 0x99, 0x61, 0x78, 0x0b, 0x75, 0x59, 0x69, 0x4e, 0x95,
	0x16, 0xe6, 0x62, 0xe0, 0x8d, 0xbc, 0x71, 0x37, 0x5a, 0x26, 0xf0, 0x0b, 0x74, 0x27, 0x17, 0xf2,
	0x44, 0xd8, 0xf2, 0x93, 0x44, 0x81, 0x19, 0xdc, 0x18, 0x79, 0xe3, 0xdb, 0xfb, 0x43, 0x52, 0x11,
	0x20, 0x96, 0x00, 0xa9, 0x09, 0x90, 0x23, 0x25, 0xe4, 0x61, 0x67, 0xfa, 0x7d, 0xbb, 0x15, 0xf5,
	0x72, 0x21, 0xdd, 0x90, 0x23, 0x05, 0x06, 0x53, 0x74, 0xbf, 0x6a, 0x01, 0x65, 0x0c, 0x89, 0x16,
	0x85, 0x11, 0x4a, 0xc2, 0xa0, 0x3d, 0x6a, 0x8f, 0xbb, 0x11, 0x76, 0xd0, 0xf1, 0x2a, 0x72, 0xb0,
	0xf5, 0xe1, 0xd7, 0xe7, 0x9d, 0xcd, 0x66, 0x3f, 0x6b, 0x9c, 0xc3, 0x21, 0xda, 0x5c, 0x4b, 0x45,
	0x1c, 0x0a, 0x25, 0x81, 0x87, 0xdf, 0x3c, 0xd4, 0x9b, 0x40, 0xf6, 0xb2, 0x94, 0xa9, 0x03, 0xf1,
	0x00, 0x6d, 0x24, 0x9a, 0x33, 0xa3, 0x74, 0xad, 0xae, 0x09, 0xb1, 0x8f, 0x6e, 0xa5, 0xa5, 0x66,
	0x76, 0xa0, 0x53, 0xd5, 0x89, 0x16, 0x31, 0xe6, 0x68, 0x83, 0xe5, 0xaa, 0x94, 0xa6, 0x22, 0xf9,
	0x4f, 0xc1, 0x4f, 0xac, 0xe0, 0x4f, 0x3f, 0xb6, 0xc7, 0x99, 0x30, 0xa7, 0x65, 0x4c, 0x12, 0x95,
	0xd3, 0xfa, 0x78, 0x2a, 0xb3, 0x0b, 0xe9, 0x5b, 0x6a, 0x2e, 0x0a, 0x0e, 0xee, 0x07, 0x88, 0x9a,
	0xde, 0x18, 0xa3, 0x0e, 0x14, 0x3c, 0x19, 0x74, 0x1c, 0x33, 0xe7, 0x1f, 0x0c, 0xad, 0xf4, 0xfe,
	0x8a, 0xf4, 0x85, 0x96, 0xf0, 0x01, 0xea, 0xaf, 0xc6, 0x8d, 0xe8, 0xfd, 0xa9, 0x87, 0xda, 0x13,
	0xc8, 0x70, 0x8a, 0x7a, 0x57, 0xce, 0xf6, 0x11, 0xf9, 0xd3, 0x7d, 0x22, 0x6b, 0xbb, 0xf3, 0x77,
	0xaf, 0x55, 0xd6, 0x4c, 0xc3, 0x6f, 0x50, 0x77, 0xb9, 0xde, 0xf0, 0xaf, 0xff, 0x2e, 0x6a, 0xfc,
	0x9d, 0xff, 0xd7, 0x34, 0xcd, 0x0f, 0x9f, 0x4d, 0x67, 0x81, 0x77, 0x39, 0x0b, 0xbc, 0x9f, 0xb3,
	0xc0, 0xfb, 0x38, 0x0f, 0x5a, 0x97, 0xf3, 0xa0, 0xf5, 0x75, 0x1e, 0xb4, 0x5e, 0x3f, 0x5e, 0x59,
	0xef, 0x95, 0x57, 0x74, 0xbe, 0x7c, 0x47, 0x76, 0xc7, 0xf1, 0x4d, 0x77, 0xd9, 0x9f, 0xfe, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x2c, 0xeb, 0xca, 0xba, 0x6c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetIprpcData(ctx context.Context, in *MsgSetIprpcData, opts ...grpc.CallOption) (*MsgSetIprpcDataResponse, error)
	FundIprpc(ctx context.Context, in *MsgFundIprpc, opts ...grpc.CallOption) (*MsgFundIprpcResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetIprpcData(ctx context.Context, in *MsgSetIprpcData, opts ...grpc.CallOption) (*MsgSetIprpcDataResponse, error) {
	out := new(MsgSetIprpcDataResponse)
	err := c.cc.Invoke(ctx, "/lavanet.lava.rewards.Msg/SetIprpcData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FundIprpc(ctx context.Context, in *MsgFundIprpc, opts ...grpc.CallOption) (*MsgFundIprpcResponse, error) {
	out := new(MsgFundIprpcResponse)
	err := c.cc.Invoke(ctx, "/lavanet.lava.rewards.Msg/FundIprpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetIprpcData(context.Context, *MsgSetIprpcData) (*MsgSetIprpcDataResponse, error)
	FundIprpc(context.Context, *MsgFundIprpc) (*MsgFundIprpcResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetIprpcData(ctx context.Context, req *MsgSetIprpcData) (*MsgSetIprpcDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIprpcData not implemented")
}
func (*UnimplementedMsgServer) FundIprpc(ctx context.Context, req *MsgFundIprpc) (*MsgFundIprpcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundIprpc not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetIprpcData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetIprpcData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetIprpcData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lavanet.lava.rewards.Msg/SetIprpcData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetIprpcData(ctx, req.(*MsgSetIprpcData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FundIprpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFundIprpc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FundIprpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lavanet.lava.rewards.Msg/FundIprpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FundIprpc(ctx, req.(*MsgFundIprpc))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lavanet.lava.rewards.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetIprpcData",
			Handler:    _Msg_SetIprpcData_Handler,
		},
		{
			MethodName: "FundIprpc",
			Handler:    _Msg_FundIprpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lavanet/lava/rewards/tx.proto",
}

func (m *MsgSetIprpcData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetIprpcData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetIprpcData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IprpcSubscriptions) > 0 {
		for iNdEx := len(m.IprpcSubscriptions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.IprpcSubscriptions[iNdEx])
			copy(dAtA[i:], m.IprpcSubscriptions[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.IprpcSubscriptions[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size, err := m.MinIprpcCost.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetIprpcDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetIprpcDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetIprpcDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgFundIprpc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundIprpc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundIprpc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Spec) > 0 {
		i -= len(m.Spec)
		copy(dAtA[i:], m.Spec)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Spec)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amounts) > 0 {
		for iNdEx := len(m.Amounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Duration != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Duration))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFundIprpcResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFundIprpcResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFundIprpcResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetIprpcData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MinIprpcCost.Size()
	n += 1 + l + sovTx(uint64(l))
	if len(m.IprpcSubscriptions) > 0 {
		for _, s := range m.IprpcSubscriptions {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgSetIprpcDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgFundIprpc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Duration != 0 {
		n += 1 + sovTx(uint64(m.Duration))
	}
	if len(m.Amounts) > 0 {
		for _, e := range m.Amounts {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.Spec)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFundIprpcResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetIprpcData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetIprpcData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetIprpcData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinIprpcCost", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinIprpcCost.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IprpcSubscriptions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IprpcSubscriptions = append(m.IprpcSubscriptions, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetIprpcDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetIprpcDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetIprpcDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFundIprpc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundIprpc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundIprpc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			m.Duration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Duration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amounts = append(m.Amounts, types.Coin{})
			if err := m.Amounts[len(m.Amounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spec = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFundIprpcResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFundIprpcResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFundIprpcResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
