endpoints:
  - chain-id: LAV1
    api-interface: tendermintrpc
    network-address: 127.0.0.1:3334
  - chain-id: LAV1
    api-interface: rest
    network-address: 127.0.0.1:3333
  - chain-id: LAV1
    api-interface: grpc
    network-address: 127.0.0.1:3335
metrics-listen-address: ":7779"