endpoints:
    - chain-id: LAV1
      api-interface: rest
      network-address: 127.0.0.1:3360
    - chain-id: LAV1
      api-interface: tendermintrpc
      network-address: 127.0.0.1:3361
    - chain-id: LAV1
      api-interface: grpc
      network-address: 127.0.0.1:3362
static-providers:
  - api-interface: tendermintrpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
  - api-interface: grpc
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220
  - api-interface: rest
    chain-id: LAV1
    node-urls:
      - url: 127.0.0.1:2220