// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pairing/relay.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RelaySession struct {
	SpecID                string                  `protobuf:"bytes,1,opt,name=specID,proto3" json:"specID,omitempty"`
	ContentHash           []byte                  `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	SessionId             uint64                  `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CuSum                 uint64                  `protobuf:"varint,4,opt,name=cu_sum,json=cuSum,proto3" json:"cu_sum,omitempty"`
	Provider              string                  `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	RelayNum              uint64                  `protobuf:"varint,6,opt,name=relay_num,json=relayNum,proto3" json:"relay_num,omitempty"`
	QoSReport             *QualityOfServiceReport `protobuf:"bytes,7,opt,name=QoSReport,proto3" json:"QoSReport,omitempty"`
	Epoch                 int64                   `protobuf:"varint,8,opt,name=epoch,proto3" json:"epoch,omitempty"`
	UnresponsiveProviders []byte                  `protobuf:"bytes,9,opt,name=unresponsive_providers,json=unresponsiveProviders,proto3" json:"unresponsive_providers,omitempty"`
	LavaChainId           string                  `protobuf:"bytes,10,opt,name=lava_chain_id,json=lavaChainId,proto3" json:"lava_chain_id,omitempty"`
	Sig                   []byte                  `protobuf:"bytes,11,opt,name=sig,proto3" json:"sig,omitempty"`
	Badge                 *Badge                  `protobuf:"bytes,12,opt,name=badge,proto3" json:"badge,omitempty"`
}

func (m *RelaySession) Reset()         { *m = RelaySession{} }
func (m *RelaySession) String() string { return proto.CompactTextString(m) }
func (*RelaySession) ProtoMessage()    {}
func (*RelaySession) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cd1bfeb9978acf, []int{0}
}
func (m *RelaySession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelaySession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelaySession.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelaySession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelaySession.Merge(m, src)
}
func (m *RelaySession) XXX_Size() int {
	return m.Size()
}
func (m *RelaySession) XXX_DiscardUnknown() {
	xxx_messageInfo_RelaySession.DiscardUnknown(m)
}

var xxx_messageInfo_RelaySession proto.InternalMessageInfo

func (m *RelaySession) GetSpecID() string {
	if m != nil {
		return m.SpecID
	}
	return ""
}

func (m *RelaySession) GetContentHash() []byte {
	if m != nil {
		return m.ContentHash
	}
	return nil
}

func (m *RelaySession) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RelaySession) GetCuSum() uint64 {
	if m != nil {
		return m.CuSum
	}
	return 0
}

func (m *RelaySession) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *RelaySession) GetRelayNum() uint64 {
	if m != nil {
		return m.RelayNum
	}
	return 0
}

func (m *RelaySession) GetQoSReport() *QualityOfServiceReport {
	if m != nil {
		return m.QoSReport
	}
	return nil
}

func (m *RelaySession) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *RelaySession) GetUnresponsiveProviders() []byte {
	if m != nil {
		return m.UnresponsiveProviders
	}
	return nil
}

func (m *RelaySession) GetLavaChainId() string {
	if m != nil {
		return m.LavaChainId
	}
	return ""
}

func (m *RelaySession) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *RelaySession) GetBadge() *Badge {
	if m != nil {
		return m.Badge
	}
	return nil
}

type RelayPrivateData struct {
	ConnectionType string `protobuf:"bytes,1,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	ApiUrl         string `protobuf:"bytes,2,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`
	Data           []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	RequestBlock   int64  `protobuf:"varint,4,opt,name=request_block,json=requestBlock,proto3" json:"request_block,omitempty"`
	ApiInterface   string `protobuf:"bytes,5,opt,name=apiInterface,proto3" json:"apiInterface,omitempty"`
	Salt           []byte `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
}

func (m *RelayPrivateData) Reset()         { *m = RelayPrivateData{} }
func (m *RelayPrivateData) String() string { return proto.CompactTextString(m) }
func (*RelayPrivateData) ProtoMessage()    {}
func (*RelayPrivateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cd1bfeb9978acf, []int{1}
}
func (m *RelayPrivateData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayPrivateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayPrivateData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayPrivateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayPrivateData.Merge(m, src)
}
func (m *RelayPrivateData) XXX_Size() int {
	return m.Size()
}
func (m *RelayPrivateData) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayPrivateData.DiscardUnknown(m)
}

var xxx_messageInfo_RelayPrivateData proto.InternalMessageInfo

func (m *RelayPrivateData) GetConnectionType() string {
	if m != nil {
		return m.ConnectionType
	}
	return ""
}

func (m *RelayPrivateData) GetApiUrl() string {
	if m != nil {
		return m.ApiUrl
	}
	return ""
}

func (m *RelayPrivateData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RelayPrivateData) GetRequestBlock() int64 {
	if m != nil {
		return m.RequestBlock
	}
	return 0
}

func (m *RelayPrivateData) GetApiInterface() string {
	if m != nil {
		return m.ApiInterface
	}
	return ""
}

func (m *RelayPrivateData) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type RelayRequest struct {
	RelaySession    *RelaySession     `protobuf:"bytes,1,opt,name=relay_session,json=relaySession,proto3" json:"relay_session,omitempty"`
	RelayData       *RelayPrivateData `protobuf:"bytes,2,opt,name=relay_data,json=relayData,proto3" json:"relay_data,omitempty"`
	DataReliability *VRFData          `protobuf:"bytes,3,opt,name=DataReliability,proto3" json:"DataReliability,omitempty"`
}

func (m *RelayRequest) Reset()         { *m = RelayRequest{} }
func (m *RelayRequest) String() string { return proto.CompactTextString(m) }
func (*RelayRequest) ProtoMessage()    {}
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cd1bfeb9978acf, []int{2}
}
func (m *RelayRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayRequest.Merge(m, src)
}
func (m *RelayRequest) XXX_Size() int {
	return m.Size()
}
func (m *RelayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RelayRequest proto.InternalMessageInfo

func (m *RelayRequest) GetRelaySession() *RelaySession {
	if m != nil {
		return m.RelaySession
	}
	return nil
}

func (m *RelayRequest) GetRelayData() *RelayPrivateData {
	if m != nil {
		return m.RelayData
	}
	return nil
}

func (m *RelayRequest) GetDataReliability() *VRFData {
	if m != nil {
		return m.DataReliability
	}
	return nil
}

type Badge struct {
	CuAllocation uint64 `protobuf:"varint,1,opt,name=cu_allocation,json=cuAllocation,proto3" json:"cu_allocation,omitempty"`
	Epoch        int64  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	BadgePk      []byte `protobuf:"bytes,3,opt,name=badge_pk,json=badgePk,proto3" json:"badge_pk,omitempty"`
	SpecId       string `protobuf:"bytes,4,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	ProjectSig   []byte `protobuf:"bytes,5,opt,name=project_sig,json=projectSig,proto3" json:"project_sig,omitempty"`
}

func (m *Badge) Reset()         { *m = Badge{} }
func (m *Badge) String() string { return proto.CompactTextString(m) }
func (*Badge) ProtoMessage()    {}
func (*Badge) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cd1bfeb9978acf, []int{3}
}
func (m *Badge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Badge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Badge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Badge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Badge.Merge(m, src)
}
func (m *Badge) XXX_Size() int {
	return m.Size()
}
func (m *Badge) XXX_DiscardUnknown() {
	xxx_messageInfo_Badge.DiscardUnknown(m)
}

var xxx_messageInfo_Badge proto.InternalMessageInfo

func (m *Badge) GetCuAllocation() uint64 {
	if m != nil {
		return m.CuAllocation
	}
	return 0
}

func (m *Badge) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *Badge) GetBadgePk() []byte {
	if m != nil {
		return m.BadgePk
	}
	return nil
}

func (m *Badge) GetSpecId() string {
	if m != nil {
		return m.SpecId
	}
	return ""
}

func (m *Badge) GetProjectSig() []byte {
	if m != nil {
		return m.ProjectSig
	}
	return nil
}

type RelayReply struct {
	Data                  []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Sig                   []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	Nonce                 uint32 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	LatestBlock           int64  `protobuf:"varint,4,opt,name=latest_block,json=latestBlock,proto3" json:"latest_block,omitempty"`
	FinalizedBlocksHashes []byte `protobuf:"bytes,5,opt,name=finalized_blocks_hashes,json=finalizedBlocksHashes,proto3" json:"finalized_blocks_hashes,omitempty"`
	SigBlocks             []byte `protobuf:"bytes,6,opt,name=sig_blocks,json=sigBlocks,proto3" json:"sig_blocks,omitempty"`
}

func (m *RelayReply) Reset()         { *m = RelayReply{} }
func (m *RelayReply) String() string { return proto.CompactTextString(m) }
func (*RelayReply) ProtoMessage()    {}
func (*RelayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cd1bfeb9978acf, []int{4}
}
func (m *RelayReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RelayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RelayReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RelayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayReply.Merge(m, src)
}
func (m *RelayReply) XXX_Size() int {
	return m.Size()
}
func (m *RelayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayReply.DiscardUnknown(m)
}

var xxx_messageInfo_RelayReply proto.InternalMessageInfo

func (m *RelayReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RelayReply) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *RelayReply) GetNonce() uint32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *RelayReply) GetLatestBlock() int64 {
	if m != nil {
		return m.LatestBlock
	}
	return 0
}

func (m *RelayReply) GetFinalizedBlocksHashes() []byte {
	if m != nil {
		return m.FinalizedBlocksHashes
	}
	return nil
}

func (m *RelayReply) GetSigBlocks() []byte {
	if m != nil {
		return m.SigBlocks
	}
	return nil
}

type VRFData struct {
	ChainID        string `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	Epoch          int64  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Differentiator bool   `protobuf:"varint,3,opt,name=differentiator,proto3" json:"differentiator,omitempty"`
	VrfValue       []byte `protobuf:"bytes,4,opt,name=vrf_value,json=vrfValue,proto3" json:"vrf_value,omitempty"`
	VrfProof       []byte `protobuf:"bytes,5,opt,name=vrf_proof,json=vrfProof,proto3" json:"vrf_proof,omitempty"`
	ProviderSig    []byte `protobuf:"bytes,6,opt,name=provider_sig,json=providerSig,proto3" json:"provider_sig,omitempty"`
	AllDataHash    []byte `protobuf:"bytes,7,opt,name=allDataHash,proto3" json:"allDataHash,omitempty"`
	QueryHash      []byte `protobuf:"bytes,8,opt,name=queryHash,proto3" json:"queryHash,omitempty"`
	Sig            []byte `protobuf:"bytes,9,opt,name=sig,proto3" json:"sig,omitempty"`
}

func (m *VRFData) Reset()         { *m = VRFData{} }
func (m *VRFData) String() string { return proto.CompactTextString(m) }
func (*VRFData) ProtoMessage()    {}
func (*VRFData) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cd1bfeb9978acf, []int{5}
}
func (m *VRFData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VRFData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VRFData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VRFData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VRFData.Merge(m, src)
}
func (m *VRFData) XXX_Size() int {
	return m.Size()
}
func (m *VRFData) XXX_DiscardUnknown() {
	xxx_messageInfo_VRFData.DiscardUnknown(m)
}

var xxx_messageInfo_VRFData proto.InternalMessageInfo

func (m *VRFData) GetChainID() string {
	if m != nil {
		return m.ChainID
	}
	return ""
}

func (m *VRFData) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *VRFData) GetDifferentiator() bool {
	if m != nil {
		return m.Differentiator
	}
	return false
}

func (m *VRFData) GetVrfValue() []byte {
	if m != nil {
		return m.VrfValue
	}
	return nil
}

func (m *VRFData) GetVrfProof() []byte {
	if m != nil {
		return m.VrfProof
	}
	return nil
}

func (m *VRFData) GetProviderSig() []byte {
	if m != nil {
		return m.ProviderSig
	}
	return nil
}

func (m *VRFData) GetAllDataHash() []byte {
	if m != nil {
		return m.AllDataHash
	}
	return nil
}

func (m *VRFData) GetQueryHash() []byte {
	if m != nil {
		return m.QueryHash
	}
	return nil
}

func (m *VRFData) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type QualityOfServiceReport struct {
	Latency      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=latency,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"latency" yaml:"Latency"`
	Availability github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=availability,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"availability" yaml:"availability"`
	Sync         github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=sync,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"sync" yaml:"sync"`
}

func (m *QualityOfServiceReport) Reset()         { *m = QualityOfServiceReport{} }
func (m *QualityOfServiceReport) String() string { return proto.CompactTextString(m) }
func (*QualityOfServiceReport) ProtoMessage()    {}
func (*QualityOfServiceReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_10cd1bfeb9978acf, []int{6}
}
func (m *QualityOfServiceReport) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QualityOfServiceReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QualityOfServiceReport.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QualityOfServiceReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QualityOfServiceReport.Merge(m, src)
}
func (m *QualityOfServiceReport) XXX_Size() int {
	return m.Size()
}
func (m *QualityOfServiceReport) XXX_DiscardUnknown() {
	xxx_messageInfo_QualityOfServiceReport.DiscardUnknown(m)
}

var xxx_messageInfo_QualityOfServiceReport proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RelaySession)(nil), "lavanet.lava.pairing.RelaySession")
	proto.RegisterType((*RelayPrivateData)(nil), "lavanet.lava.pairing.RelayPrivateData")
	proto.RegisterType((*RelayRequest)(nil), "lavanet.lava.pairing.RelayRequest")
	proto.RegisterType((*Badge)(nil), "lavanet.lava.pairing.Badge")
	proto.RegisterType((*RelayReply)(nil), "lavanet.lava.pairing.RelayReply")
	proto.RegisterType((*VRFData)(nil), "lavanet.lava.pairing.VRFData")
	proto.RegisterType((*QualityOfServiceReport)(nil), "lavanet.lava.pairing.QualityOfServiceReport")
}

func init() { proto.RegisterFile("pairing/relay.proto", fileDescriptor_10cd1bfeb9978acf) }

var fileDescriptor_10cd1bfeb9978acf = []byte{
	// 1029 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xce, 0x3a, 0x76, 0x6c, 0xbf, 0xdd, 0xa6, 0xd5, 0x34, 0x4d, 0x97, 0x94, 0x3a, 0x66, 0x91,
	0xd2, 0x1c, 0xc0, 0x86, 0x20, 0x38, 0x20, 0x21, 0x51, 0x93, 0xd2, 0x06, 0x21, 0x9a, 0x8c, 0xa1,
	0x87, 0x5c, 0x56, 0xe3, 0xf1, 0xd8, 0x1e, 0xb2, 0xde, 0xd9, 0xce, 0xec, 0x5a, 0x98, 0x5f, 0xd1,
	0x1b, 0xff, 0x83, 0x03, 0x07, 0x8e, 0x48, 0x48, 0x3d, 0xf6, 0x88, 0x38, 0x44, 0x28, 0x39, 0x70,
	0xe7, 0x17, 0xa0, 0x79, 0xbb, 0xeb, 0xb8, 0x51, 0x88, 0x54, 0x89, 0xd3, 0xce, 0x7c, 0xf3, 0xe6,
	0x9b, 0x79, 0xef, 0xfb, 0xe6, 0x69, 0xe1, 0x76, 0xc2, 0xa4, 0x96, 0xf1, 0xb8, 0xab, 0x45, 0xc4,
	0xe6, 0x9d, 0x44, 0xab, 0x54, 0x91, 0x8d, 0x88, 0xcd, 0x58, 0x2c, 0xd2, 0x8e, 0xfd, 0x76, 0x8a,
	0x88, 0xad, 0x8d, 0xb1, 0x1a, 0x2b, 0x0c, 0xe8, 0xda, 0x51, 0x1e, 0x1b, 0xfc, 0xba, 0x0a, 0x1e,
	0xb5, 0x7b, 0xfb, 0xc2, 0x18, 0xa9, 0x62, 0xb2, 0x09, 0x6b, 0x26, 0x11, 0xfc, 0x60, 0xdf, 0x77,
	0xda, 0xce, 0x6e, 0x93, 0x16, 0x33, 0xf2, 0x0e, 0x78, 0x5c, 0xc5, 0xa9, 0x88, 0xd3, 0x70, 0xc2,
	0xcc, 0xc4, 0xaf, 0xb4, 0x9d, 0x5d, 0x8f, 0xba, 0x05, 0xf6, 0x84, 0x99, 0x09, 0xb9, 0x0f, 0x60,
	0x72, 0x96, 0x50, 0x0e, 0xfd, 0xd5, 0xb6, 0xb3, 0x5b, 0xa5, 0xcd, 0x02, 0x39, 0x18, 0x92, 0x3b,
	0xb0, 0xc6, 0xb3, 0xd0, 0x64, 0x53, 0xbf, 0x8a, 0x4b, 0x35, 0x9e, 0xf5, 0xb3, 0x29, 0xd9, 0x82,
	0x46, 0xa2, 0xd5, 0x4c, 0x0e, 0x85, 0xf6, 0x6b, 0x78, 0xe4, 0x62, 0x4e, 0xee, 0x41, 0x13, 0x13,
	0x0b, 0xe3, 0x6c, 0xea, 0xaf, 0xe1, 0xae, 0x06, 0x02, 0xdf, 0x64, 0x53, 0xf2, 0x15, 0x34, 0x8f,
	0x54, 0x9f, 0x8a, 0x44, 0xe9, 0xd4, 0xaf, 0xb7, 0x9d, 0x5d, 0x77, 0xef, 0xbd, 0xce, 0x55, 0xa9,
	0x77, 0x8e, 0x32, 0x16, 0xc9, 0x74, 0xfe, 0x74, 0xd4, 0x17, 0x7a, 0x26, 0xb9, 0xc8, 0xf7, 0xd0,
	0x8b, 0xed, 0x64, 0x03, 0x6a, 0x22, 0x51, 0x7c, 0xe2, 0x37, 0xda, 0xce, 0xee, 0x2a, 0xcd, 0x27,
	0xe4, 0x63, 0xd8, 0xcc, 0x62, 0x2d, 0x4c, 0xa2, 0x62, 0x23, 0x67, 0x22, 0x2c, 0xef, 0x65, 0xfc,
	0x26, 0x66, 0x7f, 0x67, 0x79, 0xf5, 0xb0, 0x5c, 0x24, 0x01, 0xdc, 0xb0, 0xc7, 0x87, 0x7c, 0xc2,
	0x24, 0x96, 0x02, 0x30, 0x2d, 0xd7, 0x82, 0x5f, 0x58, 0xec, 0x60, 0x48, 0x6e, 0xc1, 0xaa, 0x91,
	0x63, 0xdf, 0x45, 0x1e, 0x3b, 0x24, 0x1f, 0x42, 0x6d, 0xc0, 0x86, 0x63, 0xe1, 0x7b, 0x98, 0xca,
	0xbd, 0xab, 0x53, 0xe9, 0xd9, 0x10, 0x9a, 0x47, 0x06, 0xbf, 0x3b, 0x70, 0x0b, 0xc5, 0x3b, 0xd4,
	0x72, 0xc6, 0x52, 0xb1, 0xcf, 0x52, 0x46, 0x1e, 0xc0, 0x4d, 0xae, 0xe2, 0x58, 0xf0, 0xd4, 0x0a,
	0x91, 0xce, 0x13, 0x51, 0x28, 0xb9, 0x7e, 0x01, 0x7f, 0x3b, 0x4f, 0x04, 0xb9, 0x0b, 0x75, 0x96,
	0xc8, 0x30, 0xd3, 0x11, 0x8a, 0xd9, 0xa4, 0x6b, 0x2c, 0x91, 0xdf, 0xe9, 0x88, 0x10, 0xa8, 0x0e,
	0x59, 0xca, 0x50, 0x41, 0x8f, 0xe2, 0x98, 0xbc, 0x0b, 0x37, 0xb4, 0x78, 0x9e, 0x09, 0x93, 0x86,
	0x83, 0x48, 0xf1, 0x13, 0xd4, 0x70, 0x95, 0x7a, 0x05, 0xd8, 0xb3, 0x18, 0x09, 0xc0, 0x63, 0x89,
	0x3c, 0x88, 0x53, 0xa1, 0x47, 0x8c, 0x8b, 0x42, 0xce, 0xd7, 0x30, 0x4b, 0x6e, 0x58, 0x94, 0xa2,
	0x9a, 0x1e, 0xc5, 0x71, 0xf0, 0xb7, 0x53, 0x98, 0x90, 0xe6, 0x6c, 0xe4, 0xb1, 0x3d, 0xcd, 0xea,
	0x5e, 0xb8, 0x07, 0x33, 0x70, 0xf7, 0x82, 0xab, 0x6b, 0xb2, 0xec, 0x5f, 0x7b, 0xa3, 0x25, 0x37,
	0x3f, 0x02, 0xc8, 0x89, 0x30, 0xa1, 0x0a, 0xb2, 0xec, 0x5c, 0xc3, 0xb2, 0x54, 0x48, 0x9a, 0x5b,
	0x0f, 0x6b, 0xfa, 0x18, 0x6e, 0x22, 0x24, 0x22, 0xc9, 0x06, 0xd2, 0x7a, 0x09, 0x8b, 0xe3, 0xee,
	0xdd, 0xbf, 0x9a, 0xeb, 0x19, 0xfd, 0x12, 0xe3, 0x2f, 0xef, 0x0a, 0x7e, 0x72, 0xa0, 0x86, 0x12,
	0xda, 0x82, 0xf2, 0x2c, 0x64, 0x51, 0xa4, 0x38, 0x4b, 0xcb, 0x14, 0xab, 0xd4, 0xe3, 0xd9, 0xc3,
	0x05, 0x76, 0x61, 0xcb, 0xca, 0xb2, 0x2d, 0xdf, 0x82, 0x06, 0xea, 0x1f, 0x26, 0x27, 0x85, 0x46,
	0x75, 0x9c, 0x1f, 0x9e, 0x58, 0x4d, 0xed, 0x7b, 0xb5, 0xa6, 0xab, 0x2e, 0x3d, 0xdf, 0x21, 0xd9,
	0x06, 0x37, 0xd1, 0xea, 0x7b, 0xc1, 0xd3, 0xd0, 0xfa, 0xae, 0x86, 0xdb, 0xa0, 0x80, 0xfa, 0x72,
	0x1c, 0xfc, 0xe6, 0x00, 0x14, 0x1a, 0x24, 0xd1, 0x7c, 0xe1, 0x01, 0x67, 0xc9, 0x03, 0x85, 0x67,
	0x2b, 0x17, 0x9e, 0xdd, 0x80, 0x5a, 0xac, 0x62, 0x2e, 0xf0, 0x1a, 0x37, 0x68, 0x3e, 0xb1, 0xad,
	0x22, 0x62, 0xe9, 0x65, 0xab, 0xb8, 0x39, 0x96, 0x3b, 0xe5, 0x13, 0xb8, 0x3b, 0x92, 0x31, 0x8b,
	0xe4, 0x8f, 0x62, 0x98, 0x47, 0x19, 0x6c, 0x2b, 0xc2, 0x14, 0x57, 0xbb, 0xb3, 0x58, 0xc6, 0x0d,
	0xe6, 0x09, 0x2e, 0x62, 0x8b, 0x91, 0xe3, 0x62, 0x47, 0xe1, 0xa1, 0xa6, 0x91, 0xe3, 0x3c, 0x28,
	0x78, 0x51, 0x81, 0x7a, 0x51, 0x7b, 0xe2, 0x43, 0x1d, 0x1f, 0xe0, 0xa2, 0x93, 0x95, 0xd3, 0xff,
	0xa8, 0xea, 0x0e, 0xac, 0x0f, 0xe5, 0x68, 0x24, 0xb4, 0x88, 0x53, 0xc9, 0x52, 0xa5, 0x31, 0xa9,
	0x06, 0xbd, 0x84, 0xda, 0x9e, 0x34, 0xd3, 0xa3, 0x70, 0xc6, 0xa2, 0x4c, 0x60, 0x6a, 0x1e, 0x6d,
	0xcc, 0xf4, 0xe8, 0x99, 0x9d, 0x97, 0x8b, 0x89, 0x56, 0x6a, 0x54, 0x64, 0x62, 0x17, 0x0f, 0xed,
	0xdc, 0xd6, 0xa5, 0xec, 0x20, 0x28, 0x42, 0x7e, 0x7d, 0xb7, 0xc4, 0xfa, 0x72, 0x4c, 0xda, 0xe0,
	0xb2, 0x28, 0xb2, 0xf7, 0xb7, 0x09, 0x63, 0x57, 0xf3, 0xe8, 0x32, 0x44, 0xde, 0x86, 0xe6, 0xf3,
	0x4c, 0xe8, 0x39, 0xae, 0x37, 0xf2, 0x02, 0x2c, 0x80, 0x52, 0xa2, 0xe6, 0x42, 0xa2, 0xe0, 0xe7,
	0x0a, 0x6c, 0x5e, 0xdd, 0xff, 0xc8, 0x31, 0xd4, 0xad, 0x26, 0x31, 0x9f, 0xe7, 0x15, 0xea, 0x7d,
	0xfe, 0xf2, 0x74, 0x7b, 0xe5, 0xcf, 0xd3, 0xed, 0x9d, 0xb1, 0x4c, 0x27, 0xd9, 0xa0, 0xc3, 0xd5,
	0xb4, 0xcb, 0x95, 0x99, 0x2a, 0x53, 0x7c, 0xde, 0x37, 0xc3, 0x93, 0xae, 0x6d, 0x29, 0xa6, 0xb3,
	0x2f, 0xf8, 0x3f, 0xa7, 0xdb, 0xeb, 0x73, 0x36, 0x8d, 0x3e, 0x0d, 0xbe, 0xce, 0x69, 0x02, 0x5a,
	0x12, 0x12, 0x09, 0x1e, 0x9b, 0x31, 0x19, 0x95, 0xcf, 0x05, 0x3b, 0x4c, 0xef, 0xd1, 0x1b, 0x1f,
	0x70, 0x3b, 0x3f, 0x60, 0x99, 0x2b, 0xa0, 0xaf, 0x51, 0x93, 0x23, 0xa8, 0x9a, 0x79, 0xcc, 0x51,
	0xae, 0x66, 0xef, 0xb3, 0x37, 0x3e, 0xc2, 0xcd, 0x8f, 0xb0, 0x1c, 0x01, 0x45, 0xaa, 0xbd, 0x5f,
	0x1c, 0xa8, 0xe3, 0x63, 0x10, 0x9a, 0x3c, 0x85, 0x1a, 0x0e, 0xc9, 0x75, 0xdd, 0xa7, 0x68, 0x5c,
	0x5b, 0xed, 0x6b, 0x63, 0x92, 0x68, 0x1e, 0xac, 0x90, 0x63, 0x58, 0xcf, 0x3b, 0x56, 0x36, 0x30,
	0x5c, 0xcb, 0x81, 0xf8, 0xbf, 0x98, 0x3f, 0x70, 0x7a, 0x0f, 0x5f, 0x9e, 0xb5, 0x9c, 0x57, 0x67,
	0x2d, 0xe7, 0xaf, 0xb3, 0x96, 0xf3, 0xe2, 0xbc, 0xb5, 0xf2, 0xea, 0xbc, 0xb5, 0xf2, 0xc7, 0x79,
	0x6b, 0xe5, 0xf8, 0xc1, 0x52, 0x3d, 0x0a, 0x26, 0xfc, 0x76, 0x7f, 0xe8, 0x96, 0xff, 0x10, 0x58,
	0x94, 0xc1, 0x1a, 0xfe, 0x18, 0x7c, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x4d, 0x5d,
	0xac, 0x5b, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RelayerClient is the client API for Relayer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RelayerClient interface {
	Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayReply, error)
	RelaySubscribe(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (Relayer_RelaySubscribeClient, error)
}

type relayerClient struct {
	cc grpc1.ClientConn
}

func NewRelayerClient(cc grpc1.ClientConn) RelayerClient {
	return &relayerClient{cc}
}

func (c *relayerClient) Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayReply, error) {
	out := new(RelayReply)
	err := c.cc.Invoke(ctx, "/lavanet.lava.pairing.Relayer/Relay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayerClient) RelaySubscribe(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (Relayer_RelaySubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Relayer_serviceDesc.Streams[0], "/lavanet.lava.pairing.Relayer/RelaySubscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &relayerRelaySubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Relayer_RelaySubscribeClient interface {
	Recv() (*RelayReply, error)
	grpc.ClientStream
}

type relayerRelaySubscribeClient struct {
	grpc.ClientStream
}

func (x *relayerRelaySubscribeClient) Recv() (*RelayReply, error) {
	m := new(RelayReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RelayerServer is the server API for Relayer service.
type RelayerServer interface {
	Relay(context.Context, *RelayRequest) (*RelayReply, error)
	RelaySubscribe(*RelayRequest, Relayer_RelaySubscribeServer) error
}

// UnimplementedRelayerServer can be embedded to have forward compatible implementations.
type UnimplementedRelayerServer struct {
}

func (*UnimplementedRelayerServer) Relay(ctx context.Context, req *RelayRequest) (*RelayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Relay not implemented")
}
func (*UnimplementedRelayerServer) RelaySubscribe(req *RelayRequest, srv Relayer_RelaySubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method RelaySubscribe not implemented")
}

func RegisterRelayerServer(s grpc1.Server, srv RelayerServer) {
	s.RegisterService(&_Relayer_serviceDesc, srv)
}

func _Relayer_Relay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerServer).Relay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lavanet.lava.pairing.Relayer/Relay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerServer).Relay(ctx, req.(*RelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Relayer_RelaySubscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RelayRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RelayerServer).RelaySubscribe(m, &relayerRelaySubscribeServer{stream})
}

type Relayer_RelaySubscribeServer interface {
	Send(*RelayReply) error
	grpc.ServerStream
}

type relayerRelaySubscribeServer struct {
	grpc.ServerStream
}

func (x *relayerRelaySubscribeServer) Send(m *RelayReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Relayer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lavanet.lava.pairing.Relayer",
	HandlerType: (*RelayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Relay",
			Handler:    _Relayer_Relay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RelaySubscribe",
			Handler:       _Relayer_RelaySubscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pairing/relay.proto",
}

func (m *RelaySession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelaySession) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelaySession) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Badge != nil {
		{
			size, err := m.Badge.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRelay(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if len(m.Sig) > 0 {
		i -= len(m.Sig)
		copy(dAtA[i:], m.Sig)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Sig)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.LavaChainId) > 0 {
		i -= len(m.LavaChainId)
		copy(dAtA[i:], m.LavaChainId)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.LavaChainId)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.UnresponsiveProviders) > 0 {
		i -= len(m.UnresponsiveProviders)
		copy(dAtA[i:], m.UnresponsiveProviders)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.UnresponsiveProviders)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Epoch != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x40
	}
	if m.QoSReport != nil {
		{
			size, err := m.QoSReport.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRelay(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.RelayNum != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.RelayNum))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Provider) > 0 {
		i -= len(m.Provider)
		copy(dAtA[i:], m.Provider)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Provider)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CuSum != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.CuSum))
		i--
		dAtA[i] = 0x20
	}
	if m.SessionId != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.SessionId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ContentHash) > 0 {
		i -= len(m.ContentHash)
		copy(dAtA[i:], m.ContentHash)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.ContentHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SpecID) > 0 {
		i -= len(m.SpecID)
		copy(dAtA[i:], m.SpecID)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.SpecID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RelayPrivateData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayPrivateData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayPrivateData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Salt) > 0 {
		i -= len(m.Salt)
		copy(dAtA[i:], m.Salt)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Salt)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ApiInterface) > 0 {
		i -= len(m.ApiInterface)
		copy(dAtA[i:], m.ApiInterface)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.ApiInterface)))
		i--
		dAtA[i] = 0x2a
	}
	if m.RequestBlock != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.RequestBlock))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ApiUrl) > 0 {
		i -= len(m.ApiUrl)
		copy(dAtA[i:], m.ApiUrl)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.ApiUrl)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ConnectionType) > 0 {
		i -= len(m.ConnectionType)
		copy(dAtA[i:], m.ConnectionType)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.ConnectionType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RelayRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DataReliability != nil {
		{
			size, err := m.DataReliability.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRelay(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.RelayData != nil {
		{
			size, err := m.RelayData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRelay(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.RelaySession != nil {
		{
			size, err := m.RelaySession.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRelay(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Badge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Badge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Badge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProjectSig) > 0 {
		i -= len(m.ProjectSig)
		copy(dAtA[i:], m.ProjectSig)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.ProjectSig)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SpecId) > 0 {
		i -= len(m.SpecId)
		copy(dAtA[i:], m.SpecId)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.SpecId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BadgePk) > 0 {
		i -= len(m.BadgePk)
		copy(dAtA[i:], m.BadgePk)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.BadgePk)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Epoch != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if m.CuAllocation != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.CuAllocation))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RelayReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RelayReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RelayReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SigBlocks) > 0 {
		i -= len(m.SigBlocks)
		copy(dAtA[i:], m.SigBlocks)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.SigBlocks)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.FinalizedBlocksHashes) > 0 {
		i -= len(m.FinalizedBlocksHashes)
		copy(dAtA[i:], m.FinalizedBlocksHashes)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.FinalizedBlocksHashes)))
		i--
		dAtA[i] = 0x2a
	}
	if m.LatestBlock != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.LatestBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.Nonce != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Sig) > 0 {
		i -= len(m.Sig)
		copy(dAtA[i:], m.Sig)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Sig)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VRFData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VRFData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VRFData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sig) > 0 {
		i -= len(m.Sig)
		copy(dAtA[i:], m.Sig)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.Sig)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.QueryHash) > 0 {
		i -= len(m.QueryHash)
		copy(dAtA[i:], m.QueryHash)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.QueryHash)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.AllDataHash) > 0 {
		i -= len(m.AllDataHash)
		copy(dAtA[i:], m.AllDataHash)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.AllDataHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ProviderSig) > 0 {
		i -= len(m.ProviderSig)
		copy(dAtA[i:], m.ProviderSig)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.ProviderSig)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.VrfProof) > 0 {
		i -= len(m.VrfProof)
		copy(dAtA[i:], m.VrfProof)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.VrfProof)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.VrfValue) > 0 {
		i -= len(m.VrfValue)
		copy(dAtA[i:], m.VrfValue)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.VrfValue)))
		i--
		dAtA[i] = 0x22
	}
	if m.Differentiator {
		i--
		if m.Differentiator {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Epoch != 0 {
		i = encodeVarintRelay(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ChainID) > 0 {
		i -= len(m.ChainID)
		copy(dAtA[i:], m.ChainID)
		i = encodeVarintRelay(dAtA, i, uint64(len(m.ChainID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QualityOfServiceReport) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QualityOfServiceReport) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QualityOfServiceReport) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Sync.Size()
		i -= size
		if _, err := m.Sync.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRelay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Availability.Size()
		i -= size
		if _, err := m.Availability.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRelay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Latency.Size()
		i -= size
		if _, err := m.Latency.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintRelay(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintRelay(dAtA []byte, offset int, v uint64) int {
	offset -= sovRelay(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RelaySession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SpecID)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.ContentHash)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.SessionId != 0 {
		n += 1 + sovRelay(uint64(m.SessionId))
	}
	if m.CuSum != 0 {
		n += 1 + sovRelay(uint64(m.CuSum))
	}
	l = len(m.Provider)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.RelayNum != 0 {
		n += 1 + sovRelay(uint64(m.RelayNum))
	}
	if m.QoSReport != nil {
		l = m.QoSReport.Size()
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovRelay(uint64(m.Epoch))
	}
	l = len(m.UnresponsiveProviders)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.LavaChainId)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.Sig)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.Badge != nil {
		l = m.Badge.Size()
		n += 1 + l + sovRelay(uint64(l))
	}
	return n
}

func (m *RelayPrivateData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConnectionType)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.ApiUrl)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.RequestBlock != 0 {
		n += 1 + sovRelay(uint64(m.RequestBlock))
	}
	l = len(m.ApiInterface)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.Salt)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	return n
}

func (m *RelayRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RelaySession != nil {
		l = m.RelaySession.Size()
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.RelayData != nil {
		l = m.RelayData.Size()
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.DataReliability != nil {
		l = m.DataReliability.Size()
		n += 1 + l + sovRelay(uint64(l))
	}
	return n
}

func (m *Badge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CuAllocation != 0 {
		n += 1 + sovRelay(uint64(m.CuAllocation))
	}
	if m.Epoch != 0 {
		n += 1 + sovRelay(uint64(m.Epoch))
	}
	l = len(m.BadgePk)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.SpecId)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.ProjectSig)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	return n
}

func (m *RelayReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.Sig)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.Nonce != 0 {
		n += 1 + sovRelay(uint64(m.Nonce))
	}
	if m.LatestBlock != 0 {
		n += 1 + sovRelay(uint64(m.LatestBlock))
	}
	l = len(m.FinalizedBlocksHashes)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.SigBlocks)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	return n
}

func (m *VRFData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainID)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovRelay(uint64(m.Epoch))
	}
	if m.Differentiator {
		n += 2
	}
	l = len(m.VrfValue)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.VrfProof)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.ProviderSig)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.AllDataHash)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.QueryHash)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	l = len(m.Sig)
	if l > 0 {
		n += 1 + l + sovRelay(uint64(l))
	}
	return n
}

func (m *QualityOfServiceReport) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Latency.Size()
	n += 1 + l + sovRelay(uint64(l))
	l = m.Availability.Size()
	n += 1 + l + sovRelay(uint64(l))
	l = m.Sync.Size()
	n += 1 + l + sovRelay(uint64(l))
	return n
}

func sovRelay(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRelay(x uint64) (n int) {
	return sovRelay(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RelaySession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelaySession: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelaySession: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpecID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentHash = append(m.ContentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ContentHash == nil {
				m.ContentHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			m.SessionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuSum", wireType)
			}
			m.CuSum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CuSum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Provider = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayNum", wireType)
			}
			m.RelayNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayNum |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QoSReport", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.QoSReport == nil {
				m.QoSReport = &QualityOfServiceReport{}
			}
			if err := m.QoSReport.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnresponsiveProviders", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnresponsiveProviders = append(m.UnresponsiveProviders[:0], dAtA[iNdEx:postIndex]...)
			if m.UnresponsiveProviders == nil {
				m.UnresponsiveProviders = []byte{}
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LavaChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LavaChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sig = append(m.Sig[:0], dAtA[iNdEx:postIndex]...)
			if m.Sig == nil {
				m.Sig = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Badge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Badge == nil {
				m.Badge = &Badge{}
			}
			if err := m.Badge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RelayPrivateData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayPrivateData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayPrivateData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestBlock", wireType)
			}
			m.RequestBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiInterface", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiInterface = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Salt", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Salt = append(m.Salt[:0], dAtA[iNdEx:postIndex]...)
			if m.Salt == nil {
				m.Salt = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RelayRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelaySession", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RelaySession == nil {
				m.RelaySession = &RelaySession{}
			}
			if err := m.RelaySession.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RelayData == nil {
				m.RelayData = &RelayPrivateData{}
			}
			if err := m.RelayData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataReliability", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DataReliability == nil {
				m.DataReliability = &VRFData{}
			}
			if err := m.DataReliability.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Badge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Badge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Badge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CuAllocation", wireType)
			}
			m.CuAllocation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CuAllocation |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BadgePk", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BadgePk = append(m.BadgePk[:0], dAtA[iNdEx:postIndex]...)
			if m.BadgePk == nil {
				m.BadgePk = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpecId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpecId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectSig = append(m.ProjectSig[:0], dAtA[iNdEx:postIndex]...)
			if m.ProjectSig == nil {
				m.ProjectSig = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RelayReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RelayReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RelayReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sig = append(m.Sig[:0], dAtA[iNdEx:postIndex]...)
			if m.Sig == nil {
				m.Sig = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestBlock", wireType)
			}
			m.LatestBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FinalizedBlocksHashes", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FinalizedBlocksHashes = append(m.FinalizedBlocksHashes[:0], dAtA[iNdEx:postIndex]...)
			if m.FinalizedBlocksHashes == nil {
				m.FinalizedBlocksHashes = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigBlocks", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SigBlocks = append(m.SigBlocks[:0], dAtA[iNdEx:postIndex]...)
			if m.SigBlocks == nil {
				m.SigBlocks = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VRFData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VRFData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VRFData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Differentiator", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Differentiator = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfValue", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfValue = append(m.VrfValue[:0], dAtA[iNdEx:postIndex]...)
			if m.VrfValue == nil {
				m.VrfValue = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VrfProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VrfProof = append(m.VrfProof[:0], dAtA[iNdEx:postIndex]...)
			if m.VrfProof == nil {
				m.VrfProof = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderSig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderSig = append(m.ProviderSig[:0], dAtA[iNdEx:postIndex]...)
			if m.ProviderSig == nil {
				m.ProviderSig = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllDataHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllDataHash = append(m.AllDataHash[:0], dAtA[iNdEx:postIndex]...)
			if m.AllDataHash == nil {
				m.AllDataHash = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QueryHash = append(m.QueryHash[:0], dAtA[iNdEx:postIndex]...)
			if m.QueryHash == nil {
				m.QueryHash = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sig", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sig = append(m.Sig[:0], dAtA[iNdEx:postIndex]...)
			if m.Sig == nil {
				m.Sig = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QualityOfServiceReport) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QualityOfServiceReport: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QualityOfServiceReport: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Latency", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Latency.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Availability", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Availability.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sync", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRelay
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRelay
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Sync.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRelay(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRelay
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRelay(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRelay
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRelay
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRelay
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRelay
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRelay
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRelay        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRelay          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRelay = fmt.Errorf("proto: unexpected end of group")
)
