// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: downtime/v1/query.proto

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryDowntimeRequest is the request type for the Query/QueryDowntime RPC method.
type QueryDowntimeRequest struct {
	EpochStartBlock uint64 `protobuf:"varint,1,opt,name=epoch_start_block,json=epochStartBlock,proto3" json:"epoch_start_block,omitempty"`
}

func (m *QueryDowntimeRequest) Reset()         { *m = QueryDowntimeRequest{} }
func (m *QueryDowntimeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDowntimeRequest) ProtoMessage()    {}
func (*QueryDowntimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b6d2a2f25b3e8b, []int{0}
}
func (m *QueryDowntimeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDowntimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDowntimeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDowntimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDowntimeRequest.Merge(m, src)
}
func (m *QueryDowntimeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDowntimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDowntimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDowntimeRequest proto.InternalMessageInfo

func (m *QueryDowntimeRequest) GetEpochStartBlock() uint64 {
	if m != nil {
		return m.EpochStartBlock
	}
	return 0
}

// QueryDowntimeResponse is the response type for the Query/QueryDowntime RPC method.
type QueryDowntimeResponse struct {
	CumulativeDowntimeDuration time.Duration `protobuf:"bytes,2,opt,name=cumulative_downtime_duration,json=cumulativeDowntimeDuration,proto3,stdduration" json:"cumulative_downtime_duration"`
}

func (m *QueryDowntimeResponse) Reset()         { *m = QueryDowntimeResponse{} }
func (m *QueryDowntimeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDowntimeResponse) ProtoMessage()    {}
func (*QueryDowntimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b6d2a2f25b3e8b, []int{1}
}
func (m *QueryDowntimeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDowntimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDowntimeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDowntimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDowntimeResponse.Merge(m, src)
}
func (m *QueryDowntimeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDowntimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDowntimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDowntimeResponse proto.InternalMessageInfo

func (m *QueryDowntimeResponse) GetCumulativeDowntimeDuration() time.Duration {
	if m != nil {
		return m.CumulativeDowntimeDuration
	}
	return 0
}

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b6d2a2f25b3e8b, []int{2}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b6d2a2f25b3e8b, []int{3}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryDowntimeRequest)(nil), "lavanet.lava.downtime.v1.QueryDowntimeRequest")
	proto.RegisterType((*QueryDowntimeResponse)(nil), "lavanet.lava.downtime.v1.QueryDowntimeResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "lavanet.lava.downtime.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "lavanet.lava.downtime.v1.QueryParamsResponse")
}

func init() { proto.RegisterFile("downtime/v1/query.proto", fileDescriptor_f0b6d2a2f25b3e8b) }

var fileDescriptor_f0b6d2a2f25b3e8b = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0xca, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x45, 0x8b, 0x6c, 0x11, 0x71, 0xad, 0x58, 0x43, 0x49, 0x43, 0x40, 0x08, 0x45,
	0x77, 0x6d, 0xbd, 0x78, 0x13, 0x42, 0xef, 0x6a, 0xbd, 0x79, 0x09, 0x9b, 0x74, 0x4d, 0x83, 0x49,
	0x36, 0x4d, 0x36, 0x51, 0x2f, 0x1e, 0x7c, 0x02, 0x41, 0x0f, 0x9e, 0x7d, 0x15, 0x2f, 0x3d, 0x16,
	0xbc, 0x78, 0x52, 0x69, 0x7d, 0x10, 0xc9, 0x66, 0xd3, 0x2f, 0xed, 0x47, 0xf9, 0x7a, 0xda, 0x65,
	0xe6, 0x3f, 0xbf, 0xf9, 0x0f, 0x33, 0xf0, 0xde, 0x82, 0xbf, 0x4b, 0x44, 0x18, 0x33, 0x52, 0x4e,
	0xc8, 0xaa, 0x60, 0xd9, 0x07, 0x9c, 0x66, 0x5c, 0x70, 0x34, 0x88, 0x68, 0x49, 0x13, 0x26, 0x70,
	0xf5, 0xe2, 0x46, 0x85, 0xcb, 0x89, 0x6e, 0x04, 0x9c, 0x07, 0x11, 0x23, 0x52, 0xe7, 0x15, 0x6f,
	0xc8, 0xa2, 0xc8, 0xa8, 0x08, 0x79, 0x52, 0x57, 0xea, 0x7a, 0x1b, 0xb9, 0x2f, 0xac, 0x73, 0xfd,
	0x80, 0x07, 0x5c, 0x7e, 0x49, 0xf5, 0x53, 0xd1, 0xa1, 0x22, 0xd2, 0x34, 0x24, 0x34, 0x49, 0xb8,
	0x90, 0xb8, 0xbc, 0xce, 0x5a, 0x0e, 0xec, 0xbf, 0xac, 0x8c, 0xcd, 0x14, 0x6a, 0xce, 0x56, 0x05,
	0xcb, 0x05, 0x1a, 0xc3, 0xdb, 0x2c, 0xe5, 0xfe, 0xd2, 0xcd, 0x05, 0xcd, 0x84, 0xeb, 0x45, 0xdc,
	0x7f, 0x3b, 0x00, 0x26, 0xb0, 0xaf, 0xcd, 0x6f, 0xc9, 0xc4, 0xab, 0x2a, 0xee, 0x54, 0x61, 0xeb,
	0x23, 0xbc, 0x7b, 0xc4, 0xc8, 0x53, 0x9e, 0xe4, 0x0c, 0x31, 0x38, 0xf4, 0x8b, 0xb8, 0x88, 0xa8,
	0x08, 0x4b, 0xe6, 0x36, 0x6e, 0xdd, 0x66, 0xa4, 0x41, 0xc7, 0x04, 0x76, 0x6f, 0x7a, 0x1f, 0xd7,
	0x0e, 0x71, 0x33, 0x33, 0x9e, 0x29, 0x81, 0x73, 0x63, 0xfd, 0x7b, 0xa4, 0x7d, 0xfb, 0x33, 0x02,
	0x73, 0xfd, 0x02, 0xd4, 0xb4, 0x69, 0x54, 0x56, 0x1f, 0x22, 0xd9, 0xff, 0x05, 0xcd, 0x68, 0x9c,
	0xab, 0x09, 0xac, 0xe7, 0xf0, 0xce, 0x41, 0x54, 0x79, 0x7a, 0x0a, 0xbb, 0xa9, 0x8c, 0xc8, 0x69,
	0x7a, 0x53, 0x13, 0x9f, 0xda, 0x05, 0x56, 0x95, 0x4a, 0x3f, 0xfd, 0xd1, 0x81, 0xd7, 0x25, 0x11,
	0x7d, 0x05, 0xb0, 0xd7, 0x62, 0xa3, 0x87, 0xa7, 0x19, 0x97, 0x8d, 0xe9, 0x8f, 0xce, 0x54, 0xd7,
	0x86, 0x2d, 0xfb, 0xd3, 0xcf, 0x7f, 0x5f, 0x3a, 0x16, 0x32, 0x89, 0x2a, 0x93, 0x2f, 0x69, 0xdf,
	0x41, 0x6d, 0x10, 0x7d, 0x07, 0xf0, 0xe6, 0xc1, 0x22, 0x10, 0xbe, 0xa2, 0xd5, 0xd1, 0xd6, 0x75,
	0x72, 0xb6, 0x5e, 0x99, 0x7b, 0x2c, 0xcd, 0x8d, 0x91, 0x7d, 0xda, 0x9c, 0xbc, 0xfb, 0xfd, 0xf2,
	0x9d, 0x67, 0xeb, 0xad, 0x01, 0x36, 0x5b, 0x03, 0xfc, 0xdd, 0x1a, 0xe0, 0xf3, 0xce, 0xd0, 0x36,
	0x3b, 0x43, 0xfb, 0xb5, 0x33, 0xb4, 0xd7, 0x0f, 0x82, 0x50, 0x2c, 0x0b, 0x0f, 0xfb, 0x3c, 0x3e,
	0xa4, 0xbd, 0x6f, 0xf3, 0xbc, 0xae, 0x3c, 0x93, 0x27, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4c,
	0xe3, 0x98, 0x64, 0x5d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryParams(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	QueryDowntime(ctx context.Context, in *QueryDowntimeRequest, opts ...grpc.CallOption) (*QueryDowntimeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryParams(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/lavanet.lava.downtime.v1.Query/QueryParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryDowntime(ctx context.Context, in *QueryDowntimeRequest, opts ...grpc.CallOption) (*QueryDowntimeResponse, error) {
	out := new(QueryDowntimeResponse)
	err := c.cc.Invoke(ctx, "/lavanet.lava.downtime.v1.Query/QueryDowntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryParams(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	QueryDowntime(context.Context, *QueryDowntimeRequest) (*QueryDowntimeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryParams(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryParams not implemented")
}
func (*UnimplementedQueryServer) QueryDowntime(ctx context.Context, req *QueryDowntimeRequest) (*QueryDowntimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDowntime not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lavanet.lava.downtime.v1.Query/QueryParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryParams(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryDowntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDowntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryDowntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lavanet.lava.downtime.v1.Query/QueryDowntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryDowntime(ctx, req.(*QueryDowntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lavanet.lava.downtime.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryParams",
			Handler:    _Query_QueryParams_Handler,
		},
		{
			MethodName: "QueryDowntime",
			Handler:    _Query_QueryDowntime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "downtime/v1/query.proto",
}

func (m *QueryDowntimeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDowntimeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDowntimeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochStartBlock != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochStartBlock))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryDowntimeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDowntimeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDowntimeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.CumulativeDowntimeDuration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.CumulativeDowntimeDuration):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintQuery(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryDowntimeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochStartBlock != 0 {
		n += 1 + sovQuery(uint64(m.EpochStartBlock))
	}
	return n
}

func (m *QueryDowntimeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.CumulativeDowntimeDuration)
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryDowntimeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDowntimeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDowntimeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStartBlock", wireType)
			}
			m.EpochStartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochStartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDowntimeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDowntimeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDowntimeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeDowntimeDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.CumulativeDowntimeDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
