export const AVAILABILITY_PERCENTAGE = 0.1;
export const MAX_ALLOWED_BLOCK_LISTED_SESSION_PER_PROVIDER = 3;
export const MAX_SESSIONS_ALLOWED_PER_PROVIDER = 1000;
export const RELAY_NUMBER_INCREMENT = 1;
export const MAXIMUM_NUMBER_OF_FAILURES_ALLOWED_PER_CONSUMER_SESSION = 3;
export const PERCENTILE_TO_CALCULATE_LATENCY = 0.9;
export const MIN_PROVIDERS_FOR_SYNC = 0.6;
export const DEFAULT_DECIMAL_PRECISION = 18; // same default precision as golang cosmos sdk decimal
