export const AVAILABILITY_PERCENTAGE = 0.1;
export const MAX_ALLOWED_BLOCK_LISTED_SESSION_PER_PROVIDER = 3;
export const MAX_SESSIONS_ALLOWED_PER_PROVIDER = 1000;
export const RELAY_NUMBER_INCREMENT = 1;
